export default {
  REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',
  REQUEST_COMPLETE: 'REQUEST_COMPLETE',
  CREATED_MESSAGE: 'CREATED_MESSAGE',
  CREATED_PARANOID_MESSAGE: 'CREATED_PARANOID_MESSAGE',
  API_FAILURE: 'API_FAILURE',
  ERROR_NOT_FOUND: 'ERROR_NOT_FOUND',
  TOGGLE_MODE: 'TOGGLE_MODE',
  THROW_FILES: 'THROW_FILES',
  GET_MESSAGE: 'GET_MESSAGE',
  APPLY_PASSWORD: 'APPLY_PASSWORD',
  DECRYPTED: 'DECRYPTED',
}
